%define GDT_IDX_CODIGO_0 10 
%define GDT_IDX_DATO_0 11 
%define GDT_IDX_CODIGO_3 12 
%define GDT_IDX_DATO_3 13 
%define SEGMENTO_IDX_PANTALLA 14 
%define GDT_IDX_TSS_INIT 15
%define GDT_IDX_TSS_IDLE 16
%define GDT_IDX_TSS_RICK 17
%define GDT_IDX_TSS_MORTY 18
%define GDT_IDX_TSS_MEESEEKS_R1 19
%define GDT_IDX_TSS_MEESEEKS_R2 20
%define GDT_IDX_TSS_MEESEEKS_M1 21
%define GDT_IDX_TSS_MEESEEKS_M2 22


%define GDT_OFF_NULL_DESC (GDT_IDX_NULL_DESC << 3)
%define GDT_OFF_CODIGO_0 (GDT_IDX_CODIGO_0 << 3)
%define GDT_OFF_DATO_0 (GDT_IDX_DATO_0 << 3)
%define GDT_OFF_CODIGO_3 (GDT_IDX_CODIGO_3 << 3)
%define GDT_OFF_DATO_3 (GDT_IDX_DATO_3 << 3)
%define SEGMENTO_OFF_PANTALLA (SEGMENTO_IDX_PANTALLA << 3)
%define GDT_OFF_TSS_INIT  (GDT_IDX_TSS_INIT << 3)
%define GDT_OFF_TSS_IDLE  (GDT_IDX_TSS_IDLE << 3)
%define GDT_OFF_TSS_RICK  (GDT_IDX_TSS_RICK << 3)
%define GDT_OFF_TSS_MORTY  (GDT_IDX_TSS_MORTY << 3)
%define GDT_OFF_TSS_MEESEEKS_R1 (GDT_IDX_TSS_MEESEEKS_R1 << 3)
%define GDT_OFF_TSS_MEESEEKS_R2 (GDT_IDX_TSS_MEESEEKS_R2 << 3)
%define GDT_OFF_TSS_MEESEEKS_M1 (GDT_IDX_TSS_MEESEEKS_M1 << 3)
%define GDT_OFF_TSS_MEESEEKS_M2 (GDT_IDX_TSS_MEESEEKS_M2 << 3)

%define EBP_INIT 0x25000
%define ESP_INIT 0x25000


%define KERNEL_PAGE_DIR     (0x00025000)
%define KERNEL_PAGE_TABLE_0 (0x00026000)
%define KERNEL_STACK        (0x00025000)
